backend:
  name: github
  repo: rodinshrestha/learn-gatsby-cms
  branch: main

publish_mode: editorial_workflow
media_folder: "public/assets/img"
public_folder: "img"

collections:
  - name: "blog" 
    label: "blog" 
    folder: "blog/_posts" 
    create: true 
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}



