backend:
  name: github
  repo: rodinshrestha/learn-gatsby-cms
  branch: main

publish_mode: editorial_workflow
media_folder: "public/assets/img"
public_folder: "img"

collections:
  - name: "Navigation" 
    label: "Navigation Menu" 
    folder: "navigation" 
    create: true 
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
  



